import type { APIRoute } from 'astro';

import { alternateUrls, getLocalizedPath, LANGUAGE_META, LANGUAGES } from '@/i18n';
import { SITE_URL } from '@/lib/config/urls';

export const prerender = true;

/**
 * Hand-written rather than generated by @astrojs/sitemap.
 *
 * The integration would publish /sitemap-index.xml plus /sitemap-0.xml, and it
 * carries no per-route priority or change frequency. The Next app served a
 * single /sitemap.xml with both, robots.txt points at that exact path, and
 * search engines have it indexed -- so the path and the payload stay as they
 * were. Add a public route here when you add one to src/pages.
 *
 * Every route is published once per language, and each entry carries the full
 * xhtml:link alternate set, which is what Google asks for when hreflang is
 * declared in a sitemap rather than only in the page head.
 */
const PUBLIC_ROUTES: Array<{
  path: string;
  priority: number;
  changeFrequency: 'weekly' | 'monthly';
}> = [
  { path: '/', priority: 1, changeFrequency: 'weekly' },
  { path: '/pricing', priority: 0.9, changeFrequency: 'weekly' },
  { path: '/docs/api', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/docs/sdk', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/docs/bucket-format-v1', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/contact', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/terms', priority: 0.3, changeFrequency: 'monthly' },
  { path: '/privacy', priority: 0.3, changeFrequency: 'monthly' },
];

export const GET: APIRoute = () => {
  const lastModified = new Date().toISOString();

  const entries = PUBLIC_ROUTES.flatMap((route) => {
    const alternates = alternateUrls(route.path, SITE_URL)
      .map(
        (entry) =>
          `    <xhtml:link rel="alternate" hreflang="${LANGUAGE_META[entry.lang].htmlLang}" href="${entry.href}" />`,
      )
      .join('\n');

    return LANGUAGES.map((lang) => {
      const loc = new URL(getLocalizedPath(route.path, lang), SITE_URL).href;

      return `  <url>
    <loc>${loc}</loc>
${alternates}
    <lastmod>${lastModified}</lastmod>
    <changefreq>${route.changeFrequency}</changefreq>
    <priority>${route.priority}</priority>
  </url>`;
    });
  }).join('\n');

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries}
</urlset>
`;

  return new Response(body, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
};
